"""Business Glossary API — fetch semantic enterprise definitions."""

from pydantic import BaseModel
from typing import List, Optional
from fastapi import APIRouter, Depends
from middleware.auth import get_current_user
from models.user import User

router = APIRouter(prefix="/api/v1/glossary", tags=["Glossary"])

class GlossaryTerm(BaseModel):
    id: str
    term: str
    abbreviation: str
    definition: str
    calculation: Optional[str] = None
    steward: str
    status: str
    related_assets: List[str]

@router.get("/terms", response_model=List[GlossaryTerm])
async def get_glossary_terms(current_user: User = Depends(get_current_user)):
    return [
       {
           "id": "term_mrr",
           "term": "Monthly Recurring Revenue",
           "abbreviation": "MRR",
           "definition": "The predictable total revenue generated by the business from all active subscriptions in a given month.",
           "calculation": "SUM(active_subscriptions.monthly_price) - SUM(discounts)",
           "steward": "jane.doe@dataflow.ai",
           "status": "Certified",
           "related_assets": ["gold.fct_revenue", "silver.dim_subscriptions"]
       },
       {
           "id": "term_cac",
           "term": "Customer Acquisition Cost",
           "abbreviation": "CAC",
           "definition": "The total cost of sales and marketing efforts required to acquire a new customer.",
           "calculation": "(Total Marketing Spend + Total Sales Spend) / New Customers Acquired",
           "steward": "mark.smith@dataflow.ai",
           "status": "Draft",
           "related_assets": ["silver.fct_marketing_spend", "gold.dim_customers"]
       },
       {
           "id": "term_churn",
           "term": "Revenue Churn Rate",
           "abbreviation": "Churn",
           "definition": "The percentage of MRR lost from existing customers in a given month due to cancellations or downgrades.",
           "calculation": "Lost MRR / MRR at beginning of month",
           "steward": "jane.doe@dataflow.ai",
           "status": "In Review",
           "related_assets": ["gold.fct_revenue", "silver.dim_cancellations"]
       }
    ]
