"use client";

import React from "react";
import { Server, Database, Activity, Check, Shield, AlertTriangle, Cloud, Settings, Layers, Workflow, Bot } from "lucide-react";

export default function EcommerceTutorialDoc() {
  return (
    <div className="text-[#e2e8f0]">
      <h1 className="text-4xl font-extrabold text-white mb-6">Tutorial: Real-Time E-Commerce Analytics Engine</h1>
      <p className="text-xl text-[#94a3b8] mb-10 leading-relaxed border-b border-[#1e293b] pb-8">
        In this comprehensive tutorial, we will build a production-grade data engineering pipeline for a fictional e-commerce company, &quot;Aura Mart&quot;. You will learn how to connect multiple disparate sources, clean the data using AI, enforce data contracts, and sink a perfected Gold dataset into Snowflake for BI dashboards.
      </p>

      <div className="bg-[#111827] p-6 rounded-xl border border-[#1e293b] mb-12 shadow-lg">
         <h2 className="text-2xl font-bold text-white mb-4">Architecture Overview</h2>
         <p className="text-[#cbd5e1] mb-6 leading-relaxed">
            Our goal is to create a unified `fct_sales_revenue` table that updates in real-time. We must combine legacy transactional data with live clickstream events to predict user churn.
         </p>
         <ul className="grid grid-cols-1 md:grid-cols-2 gap-4 text-[#94a3b8]">
            <li className="flex items-center gap-3 bg-[#1e293b] p-3 rounded-lg"><Database size={18} className="text-[#3b82f6]"/> <strong>Source 1:</strong> PostgreSQL (Orders & Users)</li>
            <li className="flex items-center gap-3 bg-[#1e293b] p-3 rounded-lg"><Activity size={18} className="text-[#f59e0b]"/> <strong>Source 2:</strong> Kafka (Live Clickstreams)</li>
            <li className="flex items-center gap-3 bg-[#1e293b] p-3 rounded-lg"><Workflow size={18} className="text-[#10b981]"/> <strong>Compute:</strong> Apache Flink + Core</li>
            <li className="flex items-center gap-3 bg-[#1e293b] p-3 rounded-lg"><Cloud size={18} className="text-[#8b5cf6]"/> <strong>Destination:</strong> Snowflake (Analytics)</li>
         </ul>
      </div>

      {/* --- STEP 1 --- */}
      <div className="mb-14">
        <h2 className="text-2xl font-bold text-white flex items-center gap-3 mb-6">
          <span className="flex items-center justify-center w-8 h-8 rounded-full bg-[#3b82f6] text-white text-sm font-bold">1</span>
          Setting up Connectors & Ingestion (Bronze Layer)
        </h2>
        
        <p className="text-[#94a3b8] mb-4 leading-relaxed">
          First, we need to extract the data from Aurora PostgreSQL and land it in our data lake. We&apos;ll utilize the DataFlow AI Connectors Service to set up a Change Data Capture (CDC) stream, so we never have to run expensive nightly batch queries again.
        </p>

        <div className="bg-[#1e293b] p-6 rounded-lg font-mono text-sm text-[#cbd5e1] mb-6 border border-[#3b82f6]/20 shadow-inner">
          <p className="text-[#64748b] mb-4"># Let&apos;s ask the AI Copilot to configure the PostgreSQL CDC connector for the &apos;orders&apos; table.</p>
          <div className="flex gap-4">
             <Bot size={20} className="text-[#3b82f6] shrink-0 mt-1" />
             <p className="text-white">&quot;Connect to the production Aurora PostgreSQL instance. Set up a logical replication slot for the `orders` and `users` tables, and stream every internal mutation (INSERT/UPDATE/DELETE) into our raw Bronze S3 bucket.&quot;</p>
          </div>
        </div>

        <p className="text-[#cbd5e1] leading-relaxed">
          The AI interprets this prompt, authenticates securely into AWS via IAM roles, deploys a managed Debezium cluster, and initiates the streaming flow. As new sales occur, JSON payloads instantly land in `s3://aura-lake/bronze/orders/`. The AI Data Catalog immediately indexes these incoming tables and auto-generates definitions.
        </p>
      </div>

      {/* --- STEP 2 --- */}
      <div className="mb-14">
        <h2 className="text-2xl font-bold text-white flex items-center gap-3 mb-6">
          <span className="flex items-center justify-center w-8 h-8 rounded-full bg-[#10b981] text-white text-sm font-bold">2</span>
          Data Contracts & Governance (Silver Layer)
        </h2>
        
        <p className="text-[#94a3b8] mb-4 leading-relaxed">
          Raw data is notoriously messy. We need to construct our Silver Layer by cleansing the Bronze data. But more importantly, we must enforce a strict Data Contract. If a software engineer pushes a bad migration causing `order_amount` to become a string instead of a float, our pipeline MUST catch it before it reaches Snowflake.
        </p>

        <div className="bg-[#1e293b] p-5 rounded-lg font-mono text-sm text-[#cbd5e1] mb-6 border border-[#10b981]/20 shadow-inner overflow-x-auto">
<pre>{`-- Auto-Generated by DataFlow AI Copilot 
CREATE DATA CONTRACT silver_orders_contract 
ON TABLE silver.stg_orders (
    order_id STRUCT<uuid> NOT NULL UNIQUE,
    user_id STRUCT<uuid> NOT NULL,
    order_amount FLOAT &gt; 0.0,
    status STRING IN ('pending', 'shipped', 'delivered', 'cancelled')
)
ENFORCEMENT MODE BLOCK;
`}</pre>
        </div>

        <p className="text-[#cbd5e1] leading-relaxed">
          Should anomalous data arrive (e.g., negative order amounts or null user IDs), the pipeline will divert those corrupted rows into a dead-letter quarantine queue, allowing the system to proceed cleanly while alerting engineers via PagerDuty. Furthermore, the catalog&apos;s automated PII detector has hashed customer emails before writing to the Silver layer automatically.
        </p>
      </div>

      {/* --- STEP 3 --- */}
      <div className="mb-14">
        <h2 className="text-2xl font-bold text-white flex items-center gap-3 mb-6">
          <span className="flex items-center justify-center w-8 h-8 rounded-full bg-[#f59e0b] text-white text-sm font-bold">3</span>
          The Pipeline Canvas: Joining Clickstreams
        </h2>
        
        <p className="text-[#94a3b8] mb-4 leading-relaxed">
          Now we need to combine the Silver order data with live Kafka clickstream events to categorize user attribution (e.g. &quot;Did they buy from an Instagram ad or Organic Search?&quot;).
        </p>
        <p className="text-[#cbd5e1] leading-relaxed mb-6">
          Open the Pipeline Builder Canvas. Drag the <em>Kafka `bronze.clickstream`</em> node and the <em>`silver.stg_orders`</em> node into the grid. Connect both to a newly created PySpark Transformation node.
        </p>

        <div className="flex items-center gap-4 bg-[#8b5cf6]/10 border border-[#8b5cf6]/30 p-6 rounded-xl mb-6">
           <Layers className="text-[#8b5cf6] shrink-0" size={32} />
           <div>
              <h4 className="text-white font-bold text-lg mb-1">Stateful Watermarking</h4>
              <p className="text-[#94a3b8] text-sm leading-relaxed">Because orders often occur minutes after the initial click, the AI Engine automatically writes complex time-windowed join logic (watermarking), retaining state efficiently in memory to accommodate late-arriving mobile events.</p>
           </div>
        </div>
      </div>

      {/* --- STEP 4 --- */}
      <div className="mb-14">
        <h2 className="text-2xl font-bold text-white flex items-center gap-3 mb-6">
          <span className="flex items-center justify-center w-8 h-8 rounded-full bg-[#ef4444] text-white text-sm font-bold">4</span>
          Auto-Healing a Schema Drift
        </h2>
        
        <p className="text-[#94a3b8] mb-4 leading-relaxed">
          Let&apos;s simulate a disaster. A frontend developer changes the clickstream tracking payload schema, swapping `device_os` to `platform_os`. Normally, the PySpark cluster would crash with a `FieldNotFound` exception.
        </p>
        <p className="text-[#cbd5e1] leading-relaxed mb-6">
          With DataFlow AI, the <strong>Self-Healing Engine</strong> activates immediately. The LLM traces the error to the schema registry diff, recognizes the renaming, modifies the PySpark DAG script on the fly (`df.withColumnRenamed('platform_os', 'device_os')`), tests the patch, and prompts the Data Engineer for approval on Slack. Once clicked &quot;Approve&quot;, the cluster seamlessly resumes. Zero data loss.
        </p>
      </div>

      {/* --- STEP 5 --- */}
      <div className="mb-14">
        <h2 className="text-2xl font-bold text-white flex items-center gap-3 mb-6">
          <span className="flex items-center justify-center w-8 h-8 rounded-full bg-[#8b5cf6] text-white text-sm font-bold">5</span>
          Sinking to Snowflake (Gold Layer)
        </h2>
        
        <p className="text-[#94a3b8] mb-4 leading-relaxed">
          With the transformation complete, the resulting table `fct_sales_revenue` needs to reside in Snowflake for BI Analysts using Tableau. We drag the Snowflake Sink Node onto the canvas. The engine compiles the final output logically as a Delta Lake dataset, then optimizes the transport via Snowflake Snowpipe.
        </p>
      </div>

      {/* --- CONCLUSION --- */}
      <div className="border-t border-[#1e293b] pt-12">
         <h2 className="text-3xl font-bold text-white mb-6">Final Result: The Analytics Copilot</h2>
         <p className="text-[#94a3b8] mb-6 leading-relaxed">
            The infrastructure is completely deployed. We&apos;ve bypassed weeks of manual Terraform scripting, Airflow orchestration, and custom dbt logic simply by configuring intent. Now, any Business Analyst can open the DataFlow AI Copilot chat interface and ask:
         </p>
         <div className="bg-[#111827] border border-[#1e293b] p-6 rounded-xl shadow-lg relative max-w-2xl mx-auto">
            <div className="flex gap-4 items-start mb-6 border-b border-[#1e293b] pb-6">
               <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-[#3b82f6] to-[#8b5cf6] flex items-center justify-center text-white shrink-0">BA</div>
               <div>
                  <p className="text-white text-lg">&quot;What was the total revenue yesterday driven strictly by Mobile iOS clicks vs Android?&quot;</p>
               </div>
            </div>
            <div className="flex gap-4 items-start pt-2">
               <Bot className="text-[#10b981] shrink-0 mt-1" size={28} />
               <div>
                  <p className="text-[#cbd5e1] leading-relaxed mb-4">I found the `fct_sales_revenue` table in the Gold Snowflake database. Based on the lineage, the `platform_os` attribute is fully populated. Here&apos;s your query result:</p>
                  
                  <div className="flex gap-8 mb-4">
                     <div className="bg-[#0a0c10] p-4 rounded-lg border border-[#1e293b] flex-1">
                        <span className="text-[#94a3b8] text-xs uppercase font-bold tracking-wider">iOS Revenue</span>
                        <div className="text-2xl font-mono text-white mt-1">$142,504.00</div>
                     </div>
                     <div className="bg-[#0a0c10] p-4 rounded-lg border border-[#1e293b] flex-1">
                        <span className="text-[#94a3b8] text-xs uppercase font-bold tracking-wider">Android Revenue</span>
                        <div className="text-2xl font-mono text-white mt-1">$94,120.50</div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
    </div>
  );
}
