"""Documentation Agent — Auto-generates documentation for models, pipelines, and columns."""


class DocumentationAgent:
    """Generates human-readable documentation for data artifacts."""

    @classmethod
    def generate_column_description(cls, column_name: str, data_type: str, sample_values: list) -> str:
        """Generate a brief business description for a column based on its name and samples."""
        col = column_name.lower()

        # Common business column patterns
        descriptions = {
            "id": f"Unique identifier for the record.",
            "created_at": "Timestamp when the record was created.",
            "updated_at": "Timestamp when the record was last updated.",
            "deleted_at": "Soft-delete timestamp. NULL if record is active.",
            "is_active": "Boolean flag indicating whether the record is currently active.",
            "status": "Current status of the record.",
            "name": "Display name.",
            "email": "Email address (PII — should be masked in non-production environments).",
            "phone": "Phone number (PII — should be masked).",
            "amount": "Monetary amount in the transaction currency.",
            "total": "Computed total value.",
            "quantity": "Number of units.",
            "price": "Unit price.",
            "description": "Free-text description field.",
        }

        for pattern, desc in descriptions.items():
            if pattern in col:
                return desc

        if "_id" in col:
            ref = col.replace("_id", "").replace("_", " ")
            return f"Foreign key reference to the {ref} entity."

        if "_at" in col or "_date" in col:
            label = col.replace("_at", "").replace("_date", "").replace("_", " ")
            return f"Timestamp recording when {label} occurred."

        if "_count" in col or "_total" in col:
            label = col.replace("_count", "").replace("_total", "").replace("_", " ")
            return f"Aggregated count/total of {label}."

        return f"Column '{column_name}' of type {data_type}."

    @classmethod
    def generate_table_readme(cls, table_name: str, columns: list, description: str = "") -> str:
        """Generate a markdown README for a table."""
        lines = [
            f"# {table_name}",
            "",
            description or f"Auto-generated documentation for `{table_name}`.",
            "",
            "## Columns",
            "",
            "| Column | Type | Description |",
            "|--------|------|-------------|",
        ]

        for col in columns:
            name = col.get("name", "unknown")
            dtype = col.get("type", "unknown")
            desc = cls.generate_column_description(name, dtype, col.get("sample_values", []))
            lines.append(f"| `{name}` | `{dtype}` | {desc} |")

        lines.extend([
            "",
            "---",
            f"*Documentation auto-generated by DataFlow AI Documentation Agent.*",
        ])
        return "\n".join(lines)

    @classmethod
    def generate_pipeline_summary(cls, pipeline: dict) -> str:
        """Generate a plain-English summary of a pipeline configuration."""
        name = pipeline.get("name", "Unnamed")
        ptype = pipeline.get("pipeline_type", "ingestion")
        strategy = pipeline.get("strategy", "elt")
        tables = pipeline.get("config", {}).get("tables", [])
        schedule = pipeline.get("schedule", "manual")

        summary = f"**{name}** is a {strategy.upper()} {ptype} pipeline"
        if tables:
            summary += f" that processes {len(tables)} table(s): {', '.join(tables[:5])}"
            if len(tables) > 5:
                summary += f" (+{len(tables) - 5} more)"
        summary += f". It runs on schedule: `{schedule}`."
        return summary

    @classmethod
    def generate_model_description(cls, model: dict) -> str:
        """Generate documentation for a data model (star/snowflake schema)."""
        facts = model.get("facts", [])
        dimensions = model.get("dimensions", [])
        name = model.get("name", "Unnamed Model")

        lines = [
            f"# {name}",
            "",
            f"This data model contains **{len(facts)} fact table(s)** and **{len(dimensions)} dimension table(s)**.",
            "",
        ]

        if facts:
            lines.append("## Fact Tables")
            for f in facts:
                lines.append(f"- **{f.get('name', '?')}** — Grain: {f.get('grain', 'not specified')}")

        if dimensions:
            lines.append("\n## Dimension Tables")
            for d in dimensions:
                scd = d.get("scd_type", 1)
                lines.append(f"- **{d.get('name', '?')}** — SCD Type {scd}")

        return "\n".join(lines)
